### ISSUE TITLE
add some info about implementation

### ISSUE THREAD

**Issue by matteosister** [smpallen99/ex_ami#1]
Hi!
Many thanks for this library!!!

I'm trying to create a simple listener for all asterisk events...they are then passed in a phoennix channel.
How could you implement something like this with this library?

I think that maybe I should call **register_listener** on the Client module, but I don't understand what parameters should be passed (I'm passing a callback right now) but I get an ArgumentError.

This is what I'm doing right now:

``` elixir
ExAmi.Client.register_listener(:exami_client_asterisk, &MyModule.callback/1)
```

**Comment by smpallen99** [comment]
I just updated the readme file with an example. You should check the following in your solution:
- Make sure you have started the ex_ami application by adding it to the applications section in your mix.exs file.
- The first argument to `register_listener` is the name of the server configured in your ex_ami config entry. `:asterisk` in the readme example
- The second argument to `register_listener` is the tuple {callback/2, predicate/1} where:
  *\* `callback/2` is called with the name of the server and the event
  *\* `predicate/1` is called with the event and should return true to if the callback is to be called

**Comment by matteosister** [comment]
this is exactly what I was looking for! Many thanks...
Anyway I still get an argument error...

Here is the trace:

```
** (Mix) Could not start application ex_socket: ExSocket.start(:normal, []) returned an error: shutdown: failed to start child: ExSocket.Asterisk.EventListener
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (stdlib) gen_fsm.erl:241: :gen_fsm.send_all_state_event/2
            (ex_socket) lib/ex_socket/asterisk/event_listener.ex:5: ExSocket.Asterisk.EventListener.start_link/0
            (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:326: :supervisor.start_children/3
            (stdlib) supervisor.erl:292: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```

I'm on phoenix 1.0.0
I paste here the contents of the relevant files:

**mix.exs**

``` elixir
# Configuration for the OTP application
#
# Type `mix help compile.app` for more information
def application do
  [mod: {ExSocket, []},
   applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                  :phoenix_ecto, :mariaex, :amqp, :ex_ami]]
end
```

**config/config.exs**

``` elixir
config :ex_ami,
  servers: [
    {:asterisk, [
      {:connection, {ExAmi.TcpConnection, [
        {:host, "asterisk.host"}, {:port, 5038}
      ]}},
      {:username, "___"},
      {:secret, "___"}
    ]}
  ]
```

The main application starts a GenServer named **ExSocket.Asterisk.EventListener** with:

``` elixir
worker(ExSocket.Asterisk.EventListener, [])
```

And here is the GenServer callback module:

``` elixir
defmodule ExSocket.Asterisk.EventListener do
  use GenServer

  def start_link do
    ExAmi.Client.register_listener(:asterisk, {&__MODULE__.callback/2, fn(_) -> true end})
    GenServer.start_link(__MODULE__, [], name: :asterik_event_listener)
  end

  #def start_link do
  #  ExAmi.Client.register_listener(:asterisk, {&__MODULE__.callback/2, fn(_) -> true end})
  #  {:ok, self}
  #end

  def callback(server, event) do
    IO.puts "name: #{inspect server}, event: #{inspect event}"
  end
end
```

do you have any idea?

**Comment by smpallen99** [comment]
I'm not sure what's happening. Can you try removing the register_listener from your start_link and try starting it manually from iex. Do you still get an error? If that works ok, you might want to try running the register_listener from your GenServer init function. 

I presume your using a GenServer here because your going to add more functionality. Keep in mind that your call back is called from the ExAmi process and not your GenServer. So, if you want to act on the events in your GenServer, you will need to a cast from the call back.

Hope that helps...Steve

**Comment by matteosister** [comment]
even from iex the problem is the same....I'm struggling... :sweat:

**Comment by matteosister** [comment]
ok! It was a connection problem to asterisk...it was (obviously) my fault! Many thanks for your help...I owe you a beer :beer:

**Comment by smpallen99** [comment]
Thanks!! Please feel free to add an issue requesting a better error message. If you do, please add the specifics about the connection problem you had.
